INSERT INTO trainer VALUES(NULL, 'John');
INSERT INTO trainer VALUES(NULL, 'Sally');
INSERT INTO trainer VALUES(NULL, 'Arran');
INSERT INTO trainer VALUES(NULL, 'Ben');
INSERT INTO trainer VALUES(NULL, 'Lucy');

INSERT INTO member VALUES(NULL, 'Jake','Smith', 21, 1);
INSERT INTO member VALUES(NULL, 'Julian','Jones', 25, 2);
INSERT INTO member VALUES(NULL, 'Andy','Robinson', 32, 3);
INSERT INTO member VALUES(NULL, 'Emily','Johnson', 27, 4);
INSERT INTO member VALUES(NULL, 'Nick','Taylor' ,20, 5);
INSERT INTO member VALUES(NULL, 'James','White', 35, 1);
INSERT INTO member VALUES(NULL, 'Ryan','Brown', 32, 2);
INSERT INTO member VALUES(NULL, 'Sue', 'Sharpe',22, 3);
INSERT INTO member VALUES(NULL, 'Laura','Johnson', 23, 4);
INSERT INTO member VALUES(NULL, 'Hannah','Drake', 25, 5);

INSERT INTO _class VALUES(NULL, 'Aerobics','Mon',1);
INSERT INTO _class VALUES(NULL, 'Weights','Tue',2);
INSERT INTO _class VALUES(NULL, 'Running','Wed',3);
INSERT INTO _class VALUES(NULL, 'Swimming','Thur',4);
INSERT INTO _class VALUES(NULL, 'Yoga','Fri',1);

INSERT INTO enrolment VALUES(NULL, 1,1);
INSERT INTO enrolment VALUES(NULL, 1,2);
INSERT INTO enrolment VALUES(NULL, 1,3);
INSERT INTO enrolment VALUES(NULL, 1,4);
INSERT INTO enrolment VALUES(NULL, 2,5);
INSERT INTO enrolment VALUES(NULL, 2,1);
INSERT INTO enrolment VALUES(NULL, 3,2);
INSERT INTO enrolment VALUES(NULL, 3,3);
INSERT INTO enrolment VALUES(NULL, 3,4);
INSERT INTO enrolment VALUES(NULL, 3,5);
INSERT INTO enrolment VALUES(NULL, 4,1);
INSERT INTO enrolment VALUES(NULL, 5,2);
INSERT INTO enrolment VALUES(NULL, 5,3);
INSERT INTO enrolment VALUES(NULL, 6,4);
INSERT INTO enrolment VALUES(NULL, 7,5);
INSERT INTO enrolment VALUES(NULL, 8,1);
INSERT INTO enrolment VALUES(NULL, 9,2);
INSERT INTO enrolment VALUES(NULL, 9,3);
INSERT INTO enrolment VALUES(NULL, 10,4);
INSERT INTO enrolment VALUES(NULL, 10,5);

INSERT INTO payment VALUES(NULL, 1,100,'January');
INSERT INTO payment VALUES(NULL, 2,100,'January');
INSERT INTO payment VALUES(NULL, 3,100,'January');
INSERT INTO payment VALUES(NULL, 4,100,'January');
INSERT INTO payment VALUES(NULL, 5,100,'January');
INSERT INTO payment VALUES(NULL, 1,100,'February');
INSERT INTO payment VALUES(NULL, 2,100,'February');
INSERT INTO payment VALUES(NULL, 3,100,'February');
INSERT INTO payment VALUES(NULL, 4,100,'February');
INSERT INTO payment VALUES(NULL, 5,100,'February');
INSERT INTO payment VALUES(NULL, 1,100,'March');
INSERT INTO payment VALUES(NULL, 2,100,'March');
INSERT INTO payment VALUES(NULL, 3,100,'March');
INSERT INTO payment VALUES(NULL, 4,100,'March');
INSERT INTO payment VALUES(NULL, 5,100,'March');
INSERT INTO payment VALUES(NULL, 1,100,'April');
INSERT INTO payment VALUES(NULL, 2,100,'April');
INSERT INTO payment VALUES(NULL, 3,100,'April');
INSERT INTO payment VALUES(NULL, 4,100,'April');
INSERT INTO payment VALUES(NULL, 5,100,'April');
